### ISSUE TITLE
Issue pulling array as a single tag into a Waveform record from Omron PLCs

### ISSUE THREAD

**Issue by JTGWilson** [epics-modules/ether_ip#26]
Hi,

I've had trouble pulling a 40 element DINT array from my PLC into a 40 element waveform record.

From your documentation it looked as though I should just have been able to set the Waveform record's INP field to "intArrayTest" without specifying any [n] element and it should know to pull the whole array tagged intArrayTest from my PLC. This wasn't working so I've done some investigating to try and identify why. 

I've managed to tweak the source code to fit my use case.

The first problem I had was that the MR Request being sent to the PLC was using the waveform's NELM field as the number of tag elements, to which the PLC was giving an error response as there was only one tag sent but followed by the number 41. I fudged this by changing the wf_add_record function, init_record to not use wf->nelm as the count but just have that as 0. This then meant that it created a message that the PLC was happy with and it responded with the 40 elements of data. 

The data wasn't getting through the CIP->EPICS glue though as the waveform record was empty and in a READ_INVALID state. 

So I 've tracked this to a problem in the lock_data function as it was checking the tag elements (now 1 because of my fudging) against the received elements, which is 1 tag sent to 40 elements of data received. So I just removed the check and the data lock mutex works for me again. 

And in the wf_read function there is a check of pvt->tag->elements against rec->nelm, which I've removed to make my specific case work as this had the same problem as above.

Have Arrays been working for others as described in the manual? 

I could always make the command line tool work (ether_ip_test) as long as I didn't specify an array size with the -a flag. Verbosity 10 would show that it was creating a Request for all of intArrayTest, and receiving the whole array back from the PLC, but then presenting me with just the value of the first element as the result. If I tried to ask for an array, with -a 40 flag, it would create a Request that the PLC didn't like. It was being able to compare the successful message from the command line tool and the unsuccessful message from my EPICS IOC that started me down the path to get it working.

**Comment by JTGWilson** [comment]
Added a pull request #27 just to make it easier to see exactly what changes I made.

**Comment by kasemir** [comment]
> Have Arrays been working for others as described in the manual?

Certainly. See https://github.com/epics-modules/ether_ip/blob/a1f1ec7a22453cd9a87e55f605c8aabe854cc634/testether_ipApp/Db/test.db#L430

**Comment by kasemir** [comment]
> I've had trouble pulling a 40 element DINT array from my PLC into a 40 element waveform record.

Can you show the data type and record type?
This has been used for more than a decade without issues.

Example tag:

```
$ ether_ip_test -i 172.31.73.244 -a 62 PPSmDPUbplsD02A
Tag 'PPSmDPUbplsD02A'
DINT 17 16 13 16 17 18 14 16 16 15 15 14 15 16 13 18 15 15 15 17 16 14 15 17 14 14 16 15 14 15 18 18 15 17 19 14 15 14 14 14 15 14 14 17 15 15 15 19 14 14 15 15 14 16 15 18 15 14 14 15 14 14
```

Example waveform record:
```
record(waveform, "demo")
{
    field(DTYP, "EtherIP")
    field(SCAN, "I/O Intr")
    field(INP,  "@$(PLC) PPSmDPUbplsD02A S .5")
    field(NELM, "62")
    field(FTVL, "LONG")
}
```

Example IOC:
```
$ eipIoc -p MB=172.31.73.244 -m PLC=MB -d x.db 
...
epics> dbl
demo
epics> drvEtherIP_dump
PLC MB
PPSmDPUbplsD02A DINT 15 16 14 16 14 14 18 17 16 15 13 15 14 16 15 14 15 13 17 13 15 17 15 16 15 14 16 15 15 14 13 15 15 15 16 16 15 16 16 15 14 17 15 14 14 15 15 15 15 14 14 15 18 16 15 16 15 17 15 15 16 14
```

**Comment by JTGWilson** [comment]
I can show the problem we have using just the command line tool.

Not specifying the array size as part of the request works, but just shows the first value in the array

`$ ether_ip_test -i 148.79.130.71 intArrayTest
Tag 'intArrayTest'
DINT 1
1 test runs, 0.0548561 seconds -> 54.856062 ms / tag`

Using the verbosity flag I can see in the messages sent and received, and that all the array data is being sent even though only the first element is returned by the command line tool.

`Data sent (72 bytes):
00000000 6F 00 30 00 4A 01 28 00 00 00 00 00 30 30 30 30 - o.0.J.(.....0000
00000010 30 30 30 38 00 00 00 00 00 00 00 00 00 00 02 00 - 0008............
00000020 00 00 00 00 B2 00 20 00 52 02 20 06 24 01 0A F0 - ...... .R. .$...
00000030 12 00 4C 07 91 0C 69 6E 74 41 72 72 61 79 54 65 - ..L...intArrayTe
00000040 73 74 01 00 01 00 01 00                         - st......
Data Received (206 bytes):
00000000 6F 00 B6 00 4A 01 28 00 00 00 00 00 30 30 30 30 - o...J.(.....0000
00000010 30 30 30 38 00 00 00 00 00 00 00 00 00 00 02 00 - 0008............
00000020 00 00 00 00 B2 00 A6 00 CC 00 00 00 C4 00 01 00 - ................
00000030 00 00 02 00 00 00 03 00 00 00 04 00 00 00 05 00 - ................
00000040 00 00 06 00 00 00 07 00 00 00 08 00 00 00 09 00 - ................
00000050 00 00 0A 00 00 00 0B 00 00 00 0C 00 00 00 0D 00 - ................
00000060 00 00 0E 00 00 00 0F 00 00 00 10 00 00 00 11 00 - ................
00000070 00 00 12 00 00 00 13 00 00 00 14 00 00 00 15 00 - ................
00000080 00 00 16 00 00 00 17 00 00 00 18 00 00 00 19 00 - ................
00000090 00 00 1A 00 00 00 1B 00 00 00 1C 00 00 00 1D 00 - ................
000000A0 00 00 1E 00 00 00 1F 00 00 00 20 00 00 00 21 00 - .......... ...!.
000000B0 00 00 22 00 00 00 23 00 00 00 24 00 00 00 25 00 - .."...#...$...%.
000000C0 00 00 26 00 00 00 27 00 00 00 28 00 00 00       - ..&...'...(...
DINT 1
`

But if I use the array flag -a to specify that I want 40 elements then I get the following error:

`$ ether_ip_test -i 148.79.130.71 -a 40 intArrayTest
Tag 'intArrayTest'
MR_Response:
    USINT service         = 0xCC (Response to CIP_ReadData)
    USINT reserved        = 0x00
    USINT status          = 0x20 (<unknown>)
    USINT ext. stat. size = 1
    ext. status           = 0x8017
EIP_read_tag: Failed tag 'intArrayTest'
1 test runs, 0.0559092 seconds -> 55.909157 ms / tag
`

With higher verbosity I can see the difference in the requests sent to the PLC, which seems to be what is upsetting our Omron PLC. 

`Data sent (72 bytes):
00000000 6F 00 30 00 4B 01 2B 00 00 00 00 00 30 30 30 30 - o.0.K.+.....0000
00000010 30 30 30 38 00 00 00 00 00 00 00 00 00 00 02 00 - 0008............
00000020 00 00 00 00 B2 00 20 00 52 02 20 06 24 01 0A F0 - ...... .R. .$...
00000030 12 00 4C 07 91 0C 69 6E 74 41 72 72 61 79 54 65 - ..L...intArrayTe
00000040 73 74 28 00 01 00 01 00                         - st(.....
Data Received (46 bytes):
00000000 6F 00 16 00 4B 01 2B 00 00 00 00 00 30 30 30 30 - o...K.+.....0000
00000010 30 30 30 38 00 00 00 00 00 00 00 00 00 00 02 00 - 0008............
00000020 00 00 00 00 B2 00 06 00 CC 00 20 01 17 80       - .......... ...
`

The difference is in this section of the request message

`
00000030 12 00 4C 07 91 0C 69 6E 74 41 72 72 61 79 54 65 - ..L...intArrayTe
00000040 73 74 01 00 01 00 01 00                         - st......`

compared to 

`00000030 12 00 4C 07 91 0C 69 6E 74 41 72 72 61 79 54 65 - ..L...intArrayTe
00000040 73 74 28 00 01 00 01 00                         - st(.....`

It doesn't like the inclusion of the "40 elements" after the array tag. 

The EPICS Waveform support using the NELM field to send the equivalent of the message that upsets out PLC. Do your Allen Bradley PLCs require that you specify the array length after the array tag in the request? It looks like Omron may have just implemented their CIP standard differently... for some reason...

**Comment by kasemir** [comment]
> ...which seems to be what is upsetting our **Omron PLC**...

Ah!

Well, this driver/device support is for Interfaces Allen Bradley PLCs (ControlLogix, Compact Logix).

Reading and writing of tags uses CIP service codes that Allen Bradley provided in 1756-RM005A-EN-E.pdf "Logix5000 Data Access", there described as being specific to the ControlLogix 5000 series. They are not part of the generic EtherNet/IP specification.

It's interesting that Omron PLCs respond to the same codes, albeit it looks like they do that in a different way.
If you can find ways to support Omron PLCs, I'm open to that, but it would have to be done in a way that retains full compatibility with the operational use of this driver/device for Allen Bradley PLCs.
Easiest would be a compile-time option, or maybe a more flexible flag that's set in the IOC startup file as part of the PLC IP address registration.

**Comment by JTGWilson** [comment]
The ODVA list the following "commonly used" data types for CIP in their documentation:
```
1-bit (encoded into 1 byte):
 • Boolean, BOOL, Type Code 0xC1;
- 1-byte:
 • Bit string, 8 bits, BYTE, Type Code 0xD1;
 • Unsigned 8-bit integer, USINT, Type Code 0xC6;
 • Signed 8-bit integer, SINT, Type Code 0xC2;
- 2-byte:
 • Bit string, 16-bits, WORD, Type Code 0xD2;
 • Unsigned 16-bit integer, UINT, Type Code 0xC7;
 • Signed 16-bit integer, INT, Type Code 0xC3;
- 4-byte:
 • Bit string, 32 bits, DWORD, Type Code 0xD3;
 • Unsigned 32-bit integer, UDINT, Type Code 0xC8;
 • Signed 32-bit integer, DINT, Type Code 0xC4.
```
So I guess I was just lucky that both Omron and Rockwell both decided to follow that trend. It's a shame that they seem to have decided on slightly different ways to deal with array requests though as everything else in this drivers works perfectly for us. If I come up with an elegant solution for this driver to handle both implementations (maybe, as you suggested, by using a flag in the IOC startup or the Vendor ID sent during the initial handshaking) then I'll be sure to feed that back. 

I can see that the Allen Bradley's don't ever use the unsigned data types listed above, but I'm adding them into our version as we need them for our Omron PLCs (and I can see that you'd already done the groundwork for it). Since that addition shouldn't affect operation of this driver with the Allen Bradley PLCs I'll feed that back to you once I'm done, just in case you want to have that as available functionality. 

Thanks for helping to clear up my confusion with this issue.

**Comment by kasemir** [comment]
For the data types, I think we have 0x00C1 in https://github.com/epics-modules/ether_ip/blob/a1f1ec7a22453cd9a87e55f605c8aabe854cc634/ether_ipApp/src/ether_ip.h#L406
and 0x00D3 in https://github.com/epics-modules/ether_ip/blob/a1f1ec7a22453cd9a87e55f605c8aabe854cc634/ether_ipApp/src/ether_ip.h#L417

Feel free to add the other types, which won't cause any issues when they're simply not used.

For the array handling, the vendor ID is a good idea. It'll be more work since then we should also show the result in the `drvEtherIP_report` so we can check which way it auto-configured. Still, that might be the best way forward.
